### PR TITLE
Add pkgdown::build_site() - and slight intro addition in the readme

### PR DESCRIPTION
**Pull request by Edouard-Legoupil**
This is what I was suggesting in https://github.com/ajdamico/convey/issues/271

### CODE REVIEW

**Comment by ajdamico** [comment]
hi @Edouard-Legoupil  thank you for taking the time to test out pkgdown with convey!  i'm not so familiar with pkgdown so apologies if this is a silly question..  i think we would generally want to guide users to read [convey's bookdown website](https://guilhermejacob.github.io/context/) and readers might be confused if there's also a competing pkgdown website..  is there a compelling reason to maintain pkgdown in addition to bookdown?  i'm not sure we want to drop the bookdown website?

**Comment by ajdamico** [comment]
thanks again and apologies if i'm overlooking something obvious

**Comment by Edouard-Legoupil** [comment]
Actually the bookdown you have were 3 Rmd - just pushed them to the vignette folder - with a revised yaml.. Getting all info in a single website, makes it more simple..

**Comment by ajdamico** [comment]
hi @Edouard-Legoupil  thanks again for taking the time to implement this and apologies as I might be a bit slow to understand the new setup..  is there a link to a live website in your repo that I could view to see how this differs from the bookdown site?

**Comment by Edouard-Legoupil** [comment]
[https://edouard-Legoupil.github.io/convey](https://edouard-legoupil.github.io/convey/articles/01-Introduction.html)  -- just set up the "pages" in the setting - might need some fine polish... 
image

**Comment by Edouard-Legoupil** [comment]
and you can customize as required.. https://pkgdown.r-lib.org/articles/customise.html

**Pull request closed without merging**
